## goadmin scaffold config ##
[HttpServer]
    addr = ":8000"
    webPath = "/admin" # 若定义 webPath 则会启动内置UI页面
[Jwt]
    Secret = "{token_secret}" # 请修改
    TokenExpire = 86400
    OpenApi = []
[[Database]]
    name = "default"
    dsn = "root@tcp(127.0.0.1:3306)/go_admin?parseTime=true"
    

## application config ##
[Redis]
    addr = "127.0.0.1:6379"
